class ChillStoriesTopics:
    def __init__(self):
        self.topics = {
  "meta": {
    "version": "1.0.0",
    "theme": "chill_stories",
    "theme_name": "The Slow Lane",
    "theme_tagline": "Stories that breathe — slow down, feel more, need less",
    "description": "Stories about slow living, mindfulness, healthy eating, minimalism, nature, rest, digital balance and breathwork. The antidote to overstimulation. Every story has a quiet, warm, unhurried tone. Characters discover that less is more, slower is richer, and doing nothing is sometimes the most powerful thing.",
    "age_range": "3–9",
    "narrative_tone": "Gentle, warm, unhurried. No villains. No urgency. The conflict is always internal — too much, too fast, too loud — and the resolution is always found by slowing down and paying attention.",
    "lifestyle_areas": [
      "Slow Living & Mindfulness",
      "Healthy Eating & Food Awareness",
      "Minimalism & Less is More",
      "Nature & Outdoor Life",
      "Sleep, Rest & Doing Nothing",
      "Digital Detox & Screen Balance",
      "Breathwork & Body Awareness"
    ],
    "schema": {
      "id": "unique slug",
      "name": "Topic display name",
      "tagline": "One gentle line that opens the story",
      "age_min": "minimum age",
      "age_max": "maximum age",
      "grade": "Pre-K | Kindergarten | Primary 1 | Primary 2 | Primary 3",
      "lifestyle_area": "Which of the 7 chill areas this belongs to",
      "story_seed": "The core situation or feeling the story is built around",
      "real_life_link": "The simple daily habit or practice this story points toward",
      "difficulty": "1 to 5",
      "is_active": True
    }
  },

  "topics": [

    {
      "id": "chill-prek-001",
      "name": "The Snail Who Saw Everything",
      "tagline": "The slowest one in the garden noticed what nobody else did",
      "age_min": 3, "age_max": 4,
      "grade": "Pre-K",
      "lifestyle_area": "Slow Living & Mindfulness",
      "story_seed": "A snail moves so slowly that she notices the dew on a spider's web, a ladybug's spots, and a tiny flower nobody else saw — the fast animals missed all of it",
      "real_life_link": "Walk slowly outside once a day and notice one tiny thing you never noticed before",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "chill-prek-002",
      "name": "Where Does an Apple Come From?",
      "tagline": "Before it was in your hand it was rain, sunlight and a seed",
      "age_min": 3, "age_max": 4,
      "grade": "Pre-K",
      "lifestyle_area": "Healthy Eating & Food Awareness",
      "story_seed": "An apple tells its own story — from being a tiny blossom, to growing slowly through rain and sunshine, to being picked with care and travelling to a child's hand",
      "real_life_link": "Before eating fruit, hold it and think about where it came from — one moment of gratitude before eating",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "chill-prek-003",
      "name": "The Toy Box That Was Too Full",
      "tagline": "When everything is a favourite, nothing is",
      "age_min": 3, "age_max": 4,
      "grade": "Pre-K",
      "lifestyle_area": "Minimalism & Less is More",
      "story_seed": "A child has so many toys that the toy box won't close — one day she gives some away and discovers the three toys left are the ones she actually loves and plays with every day",
      "real_life_link": "Pick three favourite toys this week — notice how much more fun they are when they're not buried",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "chill-prek-004",
      "name": "Barefoot in the Grass",
      "tagline": "The ground has been waiting for your feet",
      "age_min": 3, "age_max": 4,
      "grade": "Pre-K",
      "lifestyle_area": "Nature & Outdoor Life",
      "story_seed": "A child who always wears shoes finally takes them off in the garden — feels the cool grass, the warm earth, the tickle of a blade of grass, and realises she has been missing a whole world underfoot",
      "real_life_link": "Go barefoot in the garden or park for five minutes — feel the ground beneath your feet",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "chill-prek-005",
      "name": "The Yawn That Went Around the World",
      "tagline": "Even the sun gets sleepy — and that is a wonderful thing",
      "age_min": 3, "age_max": 4,
      "grade": "Pre-K",
      "lifestyle_area": "Sleep, Rest & Doing Nothing",
      "story_seed": "A child yawns, the dog yawns, the cat yawns, the tree sways, the sun dips — a story about how the whole world rests together and rest is not the end of the day but its most beautiful part",
      "real_life_link": "A simple bedtime ritual — three slow breaths, name one good thing from today, close your eyes",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "chill-prek-006",
      "name": "The Little Screen That Wanted to Be a Window",
      "tagline": "What if the most interesting thing is just outside?",
      "age_min": 3, "age_max": 4,
      "grade": "Pre-K",
      "lifestyle_area": "Digital Detox & Screen Balance",
      "story_seed": "A tablet gets tired of showing the same cartoons and wishes it could show real butterflies, real mud and real rain — until the child puts it down and discovers those things were outside all along",
      "real_life_link": "One screen-free morning a week — replace it with one outdoor activity, no matter how small",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "chill-prek-007",
      "name": "The Bubble Breath",
      "tagline": "Blow out slowly — watch your worries float away",
      "age_min": 3, "age_max": 4,
      "grade": "Pre-K",
      "lifestyle_area": "Breathwork & Body Awareness",
      "story_seed": "A child learns to blow bubbles — and discovers that slow deep breaths make bigger, longer-lasting bubbles. When she is upset she blows a bubble breath and watches her worry float up and pop",
      "real_life_link": "The bubble breath — breathe in for 3 counts, breathe out slowly for 5. Do it 3 times when feeling upset",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "chill-prek-008",
      "name": "Eating the Rainbow",
      "tagline": "Your plate can look like a painting — and that means your body is happy",
      "age_min": 3, "age_max": 4,
      "grade": "Pre-K",
      "lifestyle_area": "Healthy Eating & Food Awareness",
      "story_seed": "A little girl discovers that each colour of food gives her something different — red tomatoes make her strong, orange carrots help her see, green spinach makes her grow — her plate becomes a rainbow",
      "real_life_link": "Try to have at least three different colours on your plate at every meal",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "chill-prek-009",
      "name": "The Cloud Who Had Nowhere to Be",
      "tagline": "Drifting is not laziness — sometimes it is wisdom",
      "age_min": 3, "age_max": 4,
      "grade": "Pre-K",
      "lifestyle_area": "Slow Living & Mindfulness",
      "story_seed": "A cloud has no schedule, no hurry, no destination — it simply drifts and transforms, sometimes a rabbit, sometimes a mountain. A story about the joy of having nowhere to be",
      "real_life_link": "Lie on the grass and watch clouds for five minutes — no phones, no talking, just watching",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "chill-prek-010",
      "name": "The Garden That Grew When Nobody Rushed It",
      "tagline": "You cannot make a flower grow faster by pulling it",
      "age_min": 3, "age_max": 4,
      "grade": "Pre-K",
      "lifestyle_area": "Nature & Outdoor Life",
      "story_seed": "An impatient child keeps digging up her seeds to check if they are growing yet — a wise old gardener shows her that trust and patience are the only tools a garden needs",
      "real_life_link": "Plant one seed in a cup — water it daily and simply wait. Don't dig it up.",
      "difficulty": 1,
      "is_active": True
    },

    {
      "id": "chill-kinder-001",
      "name": "The Boy Who Ate Too Fast",
      "tagline": "He finished before the food even said hello",
      "age_min": 4, "age_max": 6,
      "grade": "Kindergarten",
      "lifestyle_area": "Healthy Eating & Food Awareness",
      "story_seed": "A boy eats so fast he never tastes anything — one day a wise cook challenges him to eat one grain of rice slowly and describe everything about it. He is astonished by what he discovers",
      "real_life_link": "Put your fork down between each bite — chew slowly enough to actually taste the food",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "chill-kinder-002",
      "name": "The House With One Room",
      "tagline": "A family that had almost nothing was the happiest on the street",
      "age_min": 4, "age_max": 6,
      "grade": "Kindergarten",
      "lifestyle_area": "Minimalism & Less is More",
      "story_seed": "A child visits a friend who lives in a tiny house with very few things — but the family laughs more, plays more, and is never stressed about losing anything. A gentle story about enough being enough",
      "real_life_link": "Before asking for a new thing, ask: do I truly need this or do I just want it for today?",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "chill-kinder-003",
      "name": "Five Things I Can Hear Right Now",
      "tagline": "Close your eyes — the world is full of music you never noticed",
      "age_min": 4, "age_max": 6,
      "grade": "Kindergarten",
      "lifestyle_area": "Slow Living & Mindfulness",
      "story_seed": "A child sits quietly for the first time and starts counting sounds — a bird, the wind, her own heartbeat, a distant dog, rain on a leaf. She is astonished that this music was always playing",
      "real_life_link": "The 5-4-3-2-1 grounding practice — 5 things you see, 4 you hear, 3 you feel, 2 you smell, 1 you taste",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "chill-kinder-004",
      "name": "The Tree Who Loved Rain Days",
      "tagline": "Everyone ran inside — the tree stretched its arms wide open",
      "age_min": 4, "age_max": 6,
      "grade": "Kindergarten",
      "lifestyle_area": "Nature & Outdoor Life",
      "story_seed": "When rain comes everyone rushes indoors — but a child watches the tree outside standing perfectly still, leaves up, drinking the rain. She puts on her boots and goes outside to stand in it too",
      "real_life_link": "Go outside in light rain at least once — notice how the world smells, sounds and looks completely different",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "chill-kinder-005",
      "name": "The Afternoon Nap That Saved Everything",
      "tagline": "Rest is not wasted time — it is when your brain does its best work",
      "age_min": 4, "age_max": 6,
      "grade": "Kindergarten",
      "lifestyle_area": "Sleep, Rest & Doing Nothing",
      "story_seed": "A child refuses to nap because she thinks sleeping means missing out — but in her dream she solves the puzzle that had been frustrating her all morning. She wakes up knowing the answer",
      "real_life_link": "A 20-minute quiet time after lunch — no screens, just rest or quiet play. Let the brain sort itself out",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "chill-kinder-006",
      "name": "The Robot Child",
      "tagline": "She looked at a screen so long she forgot how to feel the sun",
      "age_min": 4, "age_max": 6,
      "grade": "Kindergarten",
      "lifestyle_area": "Digital Detox & Screen Balance",
      "story_seed": "A child spends so much time on screens that she starts to feel grey and mechanical — when her device runs out of battery she is forced outside and slowly, through sunlight and mud and laughter, she remembers she is not a robot",
      "real_life_link": "The 20-20-20 rule — every 20 minutes of screen time, look at something 20 metres away for 20 seconds",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "chill-kinder-007",
      "name": "The Belly That Knows",
      "tagline": "Your body whispers before it shouts — learn to listen early",
      "age_min": 4, "age_max": 6,
      "grade": "Kindergarten",
      "lifestyle_area": "Breathwork & Body Awareness",
      "story_seed": "A child learns that her belly tightens when she is nervous, her shoulders rise when she is scared and her chest warms when she is loved — her body is always sending messages and she learns to read them",
      "real_life_link": "Body scan at bedtime — start at your feet and move up, noticing where your body feels tight or relaxed",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "chill-kinder-008",
      "name": "The Meal That Took All Day",
      "tagline": "They grew it, cooked it, shared it — and it was the best meal ever",
      "age_min": 4, "age_max": 6,
      "grade": "Kindergarten",
      "lifestyle_area": "Healthy Eating & Food Awareness",
      "story_seed": "A family spends a whole Saturday growing vegetables, cooking together slowly and eating together without hurry — the food tastes completely different from rushed weekday meals and everyone notices",
      "real_life_link": "Cook one meal together as a family this week — let the child do one small job in the kitchen",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "chill-kinder-009",
      "name": "The Birthday With No Presents",
      "tagline": "What if the best gift was not a thing at all?",
      "age_min": 4, "age_max": 6,
      "grade": "Kindergarten",
      "lifestyle_area": "Minimalism & Less is More",
      "story_seed": "A child asks for no presents for her birthday — just experiences. Her friends each bring one hour of their time: a walk, a story, a song, a drawing together. It becomes her favourite birthday ever",
      "real_life_link": "Ask for one experience instead of one object for your next celebration — a trip, a skill, a day together",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "chill-kinder-010",
      "name": "Morning Without a Screen",
      "tagline": "The first hour of the day belongs to you — not to a device",
      "age_min": 4, "age_max": 6,
      "grade": "Kindergarten",
      "lifestyle_area": "Digital Detox & Screen Balance",
      "story_seed": "A child tries one morning without any screen — she reads, draws, watches a spider outside and eats breakfast slowly. She arrives at school feeling like she has already lived a whole day of adventures",
      "real_life_link": "No screens for the first 30 minutes after waking — replace with one quiet or outdoor activity",
      "difficulty": 2,
      "is_active": True
    },

    {
      "id": "chill-p1-001",
      "name": "The Art of Doing Nothing",
      "tagline": "He sat under a tree for one whole hour — and it changed everything",
      "age_min": 6, "age_max": 7,
      "grade": "Primary 1",
      "lifestyle_area": "Slow Living & Mindfulness",
      "story_seed": "A boy who is always busy is forced to sit under a tree for an hour with nothing to do — he is bored, then restless, then slowly he starts to notice, think, feel and eventually has the best idea of his life",
      "real_life_link": "Schedule one hour a week of completely unstructured time — no screens, no activities, no plan",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "chill-p1-002",
      "name": "Where Does Sugar Hide?",
      "tagline": "The sneaky sweetness that hides in things that don't even taste sweet",
      "age_min": 6, "age_max": 7,
      "grade": "Primary 1",
      "lifestyle_area": "Healthy Eating & Food Awareness",
      "story_seed": "A child detective discovers that sugar hides in bread, ketchup, juice and cereal — not just sweets. A story about reading what is inside food and understanding that natural food has nothing to hide",
      "real_life_link": "Read the ingredients list on one packaged food this week — find hidden sugar together",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "chill-p1-003",
      "name": "The Wardrobe With Seven Things",
      "tagline": "He wore the same seven things every week — and nobody noticed except him",
      "age_min": 6, "age_max": 7,
      "grade": "Primary 1",
      "lifestyle_area": "Minimalism & Less is More",
      "story_seed": "A boy decides to keep only seven items of clothing for a whole month — he spends zero time deciding what to wear, zero time looking for things, and discovers that simplicity feels like freedom",
      "real_life_link": "Pick your outfit for the whole week on Sunday — notice how much mental space it frees up each morning",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "chill-p1-004",
      "name": "The Forest Walk That Fixed Everything",
      "tagline": "She went in with a problem and came out without it",
      "age_min": 6, "age_max": 7,
      "grade": "Primary 1",
      "lifestyle_area": "Nature & Outdoor Life",
      "story_seed": "A girl is angry about something at school and her grandmother takes her for a walk in the forest — nobody talks about the problem, they just walk and notice things. By the time they get home the problem looks tiny",
      "real_life_link": "When feeling overwhelmed take a 10-minute walk outside before trying to solve the problem",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "chill-p1-005",
      "name": "The Bedtime That Started at Sunset",
      "tagline": "Ancient people slept with the sun — and they woke up extraordinary",
      "age_min": 6, "age_max": 7,
      "grade": "Primary 1",
      "lifestyle_area": "Sleep, Rest & Doing Nothing",
      "story_seed": "A child learns that before electricity people went to bed when the sky turned dark and woke with birdsong — she tries it for one week and discovers her dreams are richer, her mornings are lighter and her days feel longer",
      "real_life_link": "No screens one hour before bed — dim the lights, read a real book or listen to soft music",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "chill-p1-006",
      "name": "The Lake That Reflected Everything Clearly",
      "tagline": "A still mind sees the world as it really is",
      "age_min": 6, "age_max": 7,
      "grade": "Primary 1",
      "lifestyle_area": "Slow Living & Mindfulness",
      "story_seed": "A child tries to see her reflection in a lake but the wind keeps rippling it — when she sits quietly and waits, the water stills and she sees everything perfectly. A story about why a calm mind understands more",
      "real_life_link": "One minute of complete stillness before any big decision — sit, breathe, then act",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "chill-p1-007",
      "name": "Box Breathing With the Waves",
      "tagline": "The ocean breathes in and out — and so can you",
      "age_min": 6, "age_max": 7,
      "grade": "Primary 1",
      "lifestyle_area": "Breathwork & Body Awareness",
      "story_seed": "A child sits by the sea and notices waves come in slowly and go out slowly — a fisherman teaches her to breathe exactly like the waves: in for four, hold for four, out for four, hold for four",
      "real_life_link": "Box breathing — breathe in 4, hold 4, out 4, hold 4. Use before school, before sleep, before anything hard",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "chill-p1-008",
      "name": "The Screen Jar",
      "tagline": "Every hour on a screen costs one coin — what will you spend yours on?",
      "age_min": 6, "age_max": 7,
      "grade": "Primary 1",
      "lifestyle_area": "Digital Detox & Screen Balance",
      "story_seed": "A family invents a screen jar — each person gets five coins per day representing five hours. Once the coins are spent the screens are done. The child starts choosing which shows truly matter and which ones she just watches out of habit",
      "real_life_link": "Track your screen time for one week — notice which content you actually enjoyed and which was just habit",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "chill-p1-009",
      "name": "Eating With No Distractions",
      "tagline": "The most delicious meal she ever had — and all she changed was she put her phone away",
      "age_min": 6, "age_max": 7,
      "grade": "Primary 1",
      "lifestyle_area": "Healthy Eating & Food Awareness",
      "story_seed": "A family tries one meal per day with no screens, no television and no rushing — just food and talking. The food tastes better, the conversation is richer and everyone eats exactly the right amount without realising it",
      "real_life_link": "One screen-free meal a day — notice how differently the food tastes when you actually pay attention to it",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "chill-p1-010",
      "name": "The Morning the Birds Woke Her First",
      "tagline": "Before the alarm, before the screen — the world was already singing",
      "age_min": 6, "age_max": 7,
      "grade": "Primary 1",
      "lifestyle_area": "Nature & Outdoor Life",
      "story_seed": "A child wakes before her alarm for the first time and hears birds outside — she opens the window and spends ten minutes just listening before the day starts. She describes it as the best ten minutes of her week",
      "real_life_link": "Wake up ten minutes early once a week — sit by a window and simply listen before the day begins",
      "difficulty": 3,
      "is_active": True
    },

    {
      "id": "chill-p2-001",
      "name": "The Mind Monkey",
      "tagline": "There is a monkey in your head who never stops jumping — here is how to calm him",
      "age_min": 7, "age_max": 8,
      "grade": "Primary 2",
      "lifestyle_area": "Slow Living & Mindfulness",
      "story_seed": "A child discovers that Buddhist teachers call the restless mind a monkey mind — always jumping from thought to thought. She learns that you cannot stop the monkey but you can watch it without following it",
      "real_life_link": "Five minutes of watching thoughts like clouds — sit still, notice each thought, let it pass without chasing it",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "chill-p2-002",
      "name": "The Ultra-Processed Truth",
      "tagline": "If your great-grandmother wouldn't recognise it as food — think twice",
      "age_min": 7, "age_max": 8,
      "grade": "Primary 2",
      "lifestyle_area": "Healthy Eating & Food Awareness",
      "story_seed": "A child imagines showing various foods to her great-grandmother from 100 years ago — the grandmother recognises apples, bread and soup but stares in confusion at neon-coloured snacks with 40 ingredients. A story about real food vs manufactured food",
      "real_life_link": "The five ingredient rule — if a food has more than five ingredients or any you cannot pronounce, eat it rarely",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "chill-p2-003",
      "name": "The Empty Shelf",
      "tagline": "She cleared everything away and suddenly had room to think",
      "age_min": 7, "age_max": 8,
      "grade": "Primary 2",
      "lifestyle_area": "Minimalism & Less is More",
      "story_seed": "A girl clears her entire bedroom of everything except the essentials — sleeping, reading, one favourite toy. For the first time she can focus completely, sleep deeply and feel genuinely calm in her own space",
      "real_life_link": "Clear one surface completely — desk, bedside table or shelf. Notice how a clear space creates a clearer mind",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "chill-p2-004",
      "name": "Forest Bathing — Shinrin-yoku",
      "tagline": "Japanese scientists proved what grandmothers always knew — trees heal",
      "age_min": 7, "age_max": 8,
      "grade": "Primary 2",
      "lifestyle_area": "Nature & Outdoor Life",
      "story_seed": "A child learns about the Japanese practice of forest bathing — walking slowly in a forest with no destination, all phones off, only using your senses. She tries it and discovers the forest is doing something to her body she cannot explain but can feel",
      "real_life_link": "Spend 20 minutes in a park or garden with no phone — walk slowly, touch bark, smell leaves, sit on grass",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "chill-p2-005",
      "name": "The Power of Eight Hours",
      "tagline": "Everything your body repairs, your brain files, your heart processes — happens while you sleep",
      "age_min": 7, "age_max": 8,
      "grade": "Primary 2",
      "lifestyle_area": "Sleep, Rest & Doing Nothing",
      "story_seed": "A child learns what actually happens during sleep — the brain washes itself clean, memories are filed, growth hormones are released and emotions are processed. She realises that sleep is not rest from living — it is when living actually happens",
      "real_life_link": "Same sleep and wake time every day including weekends — the body thrives on rhythm",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "chill-p2-006",
      "name": "The Dopamine Trap",
      "tagline": "Every notification gives your brain a tiny hit of a drug — and it always wants more",
      "age_min": 7, "age_max": 8,
      "grade": "Primary 2",
      "lifestyle_area": "Digital Detox & Screen Balance",
      "story_seed": "A child learns that her brain releases dopamine every time she gets a notification — and that apps are designed specifically to trigger this. She realises the app is not serving her, she is serving the app",
      "real_life_link": "Turn off all non-essential notifications — notice how different the day feels when you choose when to check, not the phone",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "chill-p2-007",
      "name": "The Breath Is Always There",
      "tagline": "In every moment of chaos, your breath is a door back to calm",
      "age_min": 7, "age_max": 8,
      "grade": "Primary 2",
      "lifestyle_area": "Breathwork & Body Awareness",
      "story_seed": "A child who suffers from exam anxiety learns that no matter how panicked she feels, her breath is always available — slow exhales activate the parasympathetic nervous system and physically calm the body within 90 seconds",
      "real_life_link": "The 4-7-8 breath — inhale 4, hold 7, exhale 8. Use before tests, arguments, anything stressful",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "chill-p2-008",
      "name": "Cooking From Scratch",
      "tagline": "The moment you make something yourself it becomes ten times more delicious",
      "age_min": 7, "age_max": 8,
      "grade": "Primary 2",
      "lifestyle_area": "Healthy Eating & Food Awareness",
      "story_seed": "A child who only eats packaged food learns to make one simple dish from raw ingredients — the effort, the smell, the mess and the pride make it taste unlike anything from a packet. She understands for the first time what real food is",
      "real_life_link": "Learn to make one simple dish completely from scratch — bread, soup, salad. Anything where you touch the real ingredients",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "chill-p2-009",
      "name": "The Grateful List",
      "tagline": "She wrote three things every night — and slowly her whole world changed",
      "age_min": 7, "age_max": 8,
      "grade": "Primary 2",
      "lifestyle_area": "Slow Living & Mindfulness",
      "story_seed": "A child who feels like nothing is ever enough starts writing three good things every night before sleep — small things, ordinary things. After one month she notices she has stopped wanting more and started enjoying what already is",
      "real_life_link": "Three-things gratitude journal every night — handwritten, not typed. Tiny things count the most",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "chill-p2-010",
      "name": "The Sit Spot",
      "tagline": "One spot in nature, visited every day — becomes a whole universe",
      "age_min": 7, "age_max": 8,
      "grade": "Primary 2",
      "lifestyle_area": "Nature & Outdoor Life",
      "story_seed": "A child picks one spot — a corner of the garden, a park bench — and visits it every day for a month. She begins to notice seasonal changes, the same birds returning, the soil changing. The world reveals itself only to those who stay still long enough",
      "real_life_link": "Pick a sit spot — same place, 10 minutes, every day for two weeks. Keep a simple notebook of what you notice",
      "difficulty": 4,
      "is_active": True
    },

    {
      "id": "chill-p3-001",
      "name": "Slow Fashion — The Story of a T-Shirt",
      "tagline": "Your t-shirt has a longer story than you do",
      "age_min": 8, "age_max": 9,
      "grade": "Primary 3",
      "lifestyle_area": "Minimalism & Less is More",
      "story_seed": "A child traces her t-shirt's journey — cotton grown in one country, spun in another, sewn in another, shipped across two oceans. She begins to understand what fast fashion truly costs and why one well-made thing is worth more than ten cheap ones",
      "real_life_link": "Before buying new clothes ask — do I need this, will I wear it 30 times, can I borrow or buy secondhand?",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "chill-p3-002",
      "name": "The Gut Feeling — Your Second Brain",
      "tagline": "There are 100 million neurons in your belly — it is literally thinking",
      "age_min": 8, "age_max": 9,
      "grade": "Primary 3",
      "lifestyle_area": "Healthy Eating & Food Awareness",
      "story_seed": "A child learns that the gut has its own nervous system and produces 90% of the body's serotonin — the happiness chemical. What she eats directly affects how she feels emotionally. She begins to see food as mood",
      "real_life_link": "Add one fermented food a week — yoghurt, kimchi, kefir. Feed the gut bacteria that regulate your mood",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "chill-p3-003",
      "name": "The Attention Economy",
      "tagline": "Your attention is the most valuable thing you own — and everyone wants to take it",
      "age_min": 8, "age_max": 9,
      "grade": "Primary 3",
      "lifestyle_area": "Digital Detox & Screen Balance",
      "story_seed": "A child learns that technology companies earn money by selling her attention to advertisers — every minute she spends on the app, someone profits. She begins to think of her attention as currency and asks herself who she is choosing to spend it on",
      "real_life_link": "A weekly digital audit — which apps get the most of your time and which ones genuinely make your life better",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "chill-p3-004",
      "name": "Deep Work and Single Tasking",
      "tagline": "The most productive people in the world do one thing at a time — completely",
      "age_min": 8, "age_max": 9,
      "grade": "Primary 3",
      "lifestyle_area": "Slow Living & Mindfulness",
      "story_seed": "A child who multitasks everything — homework with music, eating while reading — discovers that her brain cannot actually do two things at once, just switches rapidly and does both worse. She tries one hour of single focus and produces the best work of her life",
      "real_life_link": "One task at a time — phone face down, one tab open, one thing until it is done. Notice the quality difference",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "chill-p3-005",
      "name": "The Wim Hof Child",
      "tagline": "Cold water, deep breathing and the mind — three tools that change the body",
      "age_min": 8, "age_max": 9,
      "grade": "Primary 3",
      "lifestyle_area": "Breathwork & Body Awareness",
      "story_seed": "A child learns about breathwork practices used by athletes and monks — how controlled breathing can change body temperature, reduce inflammation and calm the nervous system. She tries a simple morning breathing exercise and feels the physical difference immediately",
      "real_life_link": "Morning breathing — 30 deep belly breaths, then hold after exhale for as long as comfortable. Do this for one week",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "chill-p3-006",
      "name": "Ikigai — The Reason You Wake Up",
      "tagline": "The Japanese live to 100 not because of medicine — because of purpose",
      "age_min": 8, "age_max": 9,
      "grade": "Primary 3",
      "lifestyle_area": "Slow Living & Mindfulness",
      "story_seed": "A child learns about the Japanese concept of ikigai — the intersection of what you love, what you are good at, what the world needs and what you can be paid for. She starts mapping her own tiny ikigai and realises purpose is available at any age",
      "real_life_link": "Draw the four ikigai circles — what do I love, what am I good at, what does the world need, what could I give?",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "chill-p3-007",
      "name": "The Microbiome Garden",
      "tagline": "Inside your body is a garden of 38 trillion living things — are you feeding them well?",
      "age_min": 8, "age_max": 9,
      "grade": "Primary 3",
      "lifestyle_area": "Healthy Eating & Food Awareness",
      "story_seed": "A child learns she is carrying more bacterial cells than human cells — and that these bacteria control her immunity, mood, weight and energy. She begins to see healthy eating not as restriction but as gardening her inner ecosystem",
      "real_life_link": "Eat the rainbow of vegetables this week — each colour feeds different gut bacteria. Diversity is the goal",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "chill-p3-008",
      "name": "Rewilding — Going Feral for a Weekend",
      "tagline": "Humans spent 99% of their history outside — the body still remembers",
      "age_min": 8, "age_max": 9,
      "grade": "Primary 3",
      "lifestyle_area": "Nature & Outdoor Life",
      "story_seed": "A child spends a whole weekend completely outside — no screens, no indoor heating, sleeping under stars, cooking on a fire. She discovers that something ancient in her body wakes up — instincts, attention, calm — that never appear indoors",
      "real_life_link": "One night camping or sleeping with the window fully open — notice how differently you sleep under natural air and dark",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "chill-p3-009",
      "name": "The Art of Doing Nothing — Niksen",
      "tagline": "The Dutch have a word for doing nothing on purpose — and science says it is genius",
      "age_min": 8, "age_max": 9,
      "grade": "Primary 3",
      "lifestyle_area": "Sleep, Rest & Doing Nothing",
      "story_seed": "A child learns about the Dutch concept of niksen — intentional idleness. The default mode network of the brain activates only during rest and is responsible for creativity, empathy and problem solving. Being bored is not wasted time — it is when your best thinking happens",
      "real_life_link": "Schedule 20 minutes of niksen — no input, no output, no purpose. Just exist. Do it weekly",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "chill-p3-010",
      "name": "The Circadian Rhythm",
      "tagline": "Every cell in your body has a clock — and blue light from screens is breaking it",
      "age_min": 8, "age_max": 9,
      "grade": "Primary 3",
      "lifestyle_area": "Sleep, Rest & Doing Nothing",
      "story_seed": "A child learns that her body runs on a 24-hour biological clock — light tells her cells when to be awake and when to sleep. Screen light after dark confuses every cell in her body into thinking it is still daytime, disrupting everything from mood to immunity",
      "real_life_link": "Blue light glasses or night mode after sunset — and ideally no screens after 8pm. Watch how sleep quality changes",
      "difficulty": 5,
      "is_active": True
    }

  ]
}