class PlanetProtector:
    def __init__(self):
        self.topics = {
  "meta": {
    "version": "1.0.0",
    "description": "Planet Protectors — Global Topic Taxonomy. moral_value and activity_type removed — morals are drawn naturally by the story LLM, activities are a separate pipeline layer.",
    "age_range": "3–9",
    "grade_range": "Pre-K to Primary 3 / Grade 3",
    "subjects": [
      "Science & Nature",
      "Math Concepts",
      "Social Studies",
      "Values & Emotions"
    ],
    "total_topics": 120,
    "schema": {
      "id": "unique slug",
      "name": "Topic display name",
      "tagline": "One-line hook for the story generator",
      "age_min": "minimum age",
      "age_max": "maximum age",
      "grade": "Pre-K | Kindergarten | Primary 1 | Primary 2 | Primary 3",
      "subject": "subject area",
      "curriculum_tag": "universal curriculum concept",
      "env_angle": "how this topic connects to planet protection",
      "character_type": "suggested story character archetype",
      "difficulty": "1 (simplest) to 5 (most complex)",
      "is_active": True
    }
  },
  "topics": [
    {
      "id": "prek-sci-001",
      "name": "Rain and Puddles",
      "tagline": "Where does rain come from and where does it go?",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Science & Nature",
      "curriculum_tag": "Water Cycle — Basics",
      "env_angle": "Rain fills rivers and feeds plants — dirty streets hurt rain's journey",
      "character_type": "A raindrop with a personality",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-sci-002",
      "name": "Sunshine and Shadows",
      "tagline": "The sun wakes up the world every morning",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Science & Nature",
      "curriculum_tag": "Light — Sun as a source",
      "env_angle": "Sunlight is free clean energy — we don't need to burn things for light",
      "character_type": "A sunbeam on a mission",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-sci-003",
      "name": "Seeds and Sprouts",
      "tagline": "A tiny seed holds a whole tree inside it",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Science & Nature",
      "curriculum_tag": "Plants — Growth basics",
      "env_angle": "Every seed planted is a gift of oxygen and shade to the planet",
      "character_type": "A seed who is afraid to grow",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-sci-004",
      "name": "Wind and Breezes",
      "tagline": "The invisible friend that moves the world",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Science & Nature",
      "curriculum_tag": "Air — Properties",
      "env_angle": "Wind carries seeds, cleans air, and can power windmills — protect it from pollution",
      "character_type": "A playful wind gust",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-sci-005",
      "name": "Day and Night",
      "tagline": "Why does the sky go dark and light again?",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth — Day/Night cycle",
      "env_angle": "Turning off lights at night saves energy and helps nocturnal animals",
      "character_type": "The moon and sun who share the sky",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-sci-006",
      "name": "Animals and Their Homes",
      "tagline": "Every creature has a special place it calls home",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Science & Nature",
      "curriculum_tag": "Animals — Habitats basics",
      "env_angle": "Cutting trees destroys animal homes — forests are neighbourhoods for wildlife",
      "character_type": "A bird searching for a tree to nest in",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-sci-007",
      "name": "Hot and Cold",
      "tagline": "Why is the sun hot and ice cold?",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Science & Nature",
      "curriculum_tag": "Temperature — Basic sensing",
      "env_angle": "Earth is getting too hot because of pollution — we need to cool it down together",
      "character_type": "A melting snowflake who needs help",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-sci-008",
      "name": "Flowers and Colours",
      "tagline": "Why do flowers have so many beautiful colours?",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Science & Nature",
      "curriculum_tag": "Plants — Parts and purpose",
      "env_angle": "Flowers feed bees and butterflies — picking them carelessly hurts the food chain",
      "character_type": "A flower who wants to be noticed but not picked",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-sci-009",
      "name": "Soil and Mud",
      "tagline": "Dirty mud is actually magic",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Materials — Soil",
      "env_angle": "Healthy soil grows all our food — chemicals and plastic poison it",
      "character_type": "A worm who lives in the soil and keeps it healthy",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-sci-010",
      "name": "Oceans and Fish",
      "tagline": "The sea is the biggest home on Earth",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Science & Nature",
      "curriculum_tag": "Oceans — Basic awareness",
      "env_angle": "Plastic in oceans hurts fish and sea turtles — every wrapper matters",
      "character_type": "A fish tangled in a plastic bag who is rescued",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-val-001",
      "name": "Sharing is Growing",
      "tagline": "When we share, everyone gets more",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Sharing",
      "env_angle": "Earth's resources are shared by all — hoarding hurts others",
      "character_type": "Two animals sharing the last berry bush",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-val-002",
      "name": "Saying Sorry to the Earth",
      "tagline": "What happens when we make a mistake and fix it?",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Responsibility",
      "env_angle": "Littering hurts Earth — picking up rubbish is how we say sorry",
      "character_type": "A child who accidentally drops a wrapper and feels guilty",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-val-003",
      "name": "Being Kind to Bugs",
      "tagline": "Even the tiniest creature deserves kindness",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Empathy",
      "env_angle": "Insects pollinate flowers and feed birds — cruelty to them breaks the food chain",
      "character_type": "A ladybug who is scared of being stepped on",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-val-004",
      "name": "Too Much and Too Little",
      "tagline": "Using too much of anything hurts the planet",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Self-regulation",
      "env_angle": "Wasting water, food, electricity — less is more for the planet",
      "character_type": "A river that runs dry because everyone took too much",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-math-001",
      "name": "Counting Leaves",
      "tagline": "Numbers hide everywhere in nature",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Math Concepts",
      "curriculum_tag": "Numbers — Counting 1 to 10",
      "env_angle": "Counting trees in a forest shows if we are planting enough",
      "character_type": "A counting caterpillar on a leaf",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-math-002",
      "name": "Big and Small Animals",
      "tagline": "Size matters in nature — big and small both have a role",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Math Concepts",
      "curriculum_tag": "Measurement — Size comparison",
      "env_angle": "Both the biggest whale and smallest bee are equally important to the ecosystem",
      "character_type": "An elephant and an ant who help each other",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "prek-math-003",
      "name": "Sorting Nature's Treasures",
      "tagline": "Leaves, rocks, and shells — can you sort them?",
      "age_min": 3,
      "age_max": 4,
      "grade": "Pre-K",
      "subject": "Math Concepts",
      "curriculum_tag": "Classification — Sorting by attribute",
      "env_angle": "Sorting rubbish for recycling is just like sorting nature — everything in its right place",
      "character_type": "A squirrel sorting nuts by size and colour",
      "difficulty": 1,
      "is_active": True
    },
    {
      "id": "kinder-sci-001",
      "name": "Living and Non-Living Things",
      "tagline": "What makes something alive?",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Living vs non-living",
      "env_angle": "All living things need clean air, water and soil — pollution attacks all three",
      "character_type": "A child who discovers a rock can't drink water but a plant can",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-sci-002",
      "name": "The Four Seasons",
      "tagline": "Why does the world change its coat four times a year?",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Seasons",
      "env_angle": "Climate change is making seasons unpredictable — animals and plants are confused",
      "character_type": "A bear who wakes up from hibernation too early because it is too warm",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-sci-003",
      "name": "Animals and Their Food",
      "tagline": "Every animal has a favourite meal — but where does it come from?",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Animals and diet",
      "env_angle": "Destroying habitats removes food sources for wild animals",
      "character_type": "A fox whose forest berry bushes have been replaced by a car park",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-sci-004",
      "name": "Sink or Float",
      "tagline": "Why do some things float and some things sink?",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Science & Nature",
      "curriculum_tag": "Physical Science — Properties of materials",
      "env_angle": "Plastic floats in oceans and stays there for hundreds of years — it never sinks away",
      "character_type": "A sea turtle confused by a floating plastic bag that looks like a jellyfish",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-sci-005",
      "name": "Where Does Water Go?",
      "tagline": "Follow a water drop on its great journey",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Water cycle",
      "env_angle": "Polluted water completes the cycle and comes back as dirty rain",
      "character_type": "A water drop narrating its own adventure",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-sci-006",
      "name": "Butterflies and Change",
      "tagline": "A caterpillar's impossible transformation",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Life cycles",
      "env_angle": "Pesticides kill caterpillars before they become butterflies — no butterflies means fewer flowers pollinated",
      "character_type": "A caterpillar inside a cocoon dreaming of wings",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-sci-007",
      "name": "Rocks and Stones",
      "tagline": "Rocks are the oldest things you will ever touch",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Earth materials",
      "env_angle": "Mining rocks and sand destroys landscapes and rivers — use materials wisely",
      "character_type": "A old wise rock who tells the story of a mountain",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-sci-008",
      "name": "Push and Pull",
      "tagline": "Forces are everywhere — even in nature",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Science & Nature",
      "curriculum_tag": "Physical Science — Forces basics",
      "env_angle": "Wind and water forces can generate clean energy — nature gives us power for free",
      "character_type": "A leaf blown by wind that powers a tiny windmill",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-sci-009",
      "name": "The Night Sky",
      "tagline": "Stars, moon and the darkness that protects us",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Stars and Moon",
      "env_angle": "Light pollution from cities hides the stars and confuses migrating birds",
      "character_type": "A migrating bird navigating by stars who gets lost near a bright city",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-sci-010",
      "name": "Decomposers — Nature's Cleaners",
      "tagline": "Who cleans up the forest floor?",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Decomposition",
      "env_angle": "Nature recycles everything — we should recycle too",
      "character_type": "Mushrooms and worms who are unsung heroes of the forest",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-val-001",
      "name": "Feeling Angry at Pollution",
      "tagline": "It's okay to feel angry — now use it to do something",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Managing anger",
      "env_angle": "Feeling upset about littering or pollution is healthy — channel it into action",
      "character_type": "A child who sees a river being polluted and feels helpless then empowered",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-val-002",
      "name": "Helping Without Being Asked",
      "tagline": "The best help is the kind nobody asked for",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Kindness and initiative",
      "env_angle": "Picking up litter nobody asked you to pick up is a gift to the Earth",
      "character_type": "A child who quietly waters a dying plant in the park every day",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-val-003",
      "name": "Working Together",
      "tagline": "Problems too big for one are easy for many",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Cooperation",
      "env_angle": "Climate change is too big for one person — every family, school and community must work together",
      "character_type": "A group of ants building a dam to save their colony from flood",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-math-001",
      "name": "Counting Animals in the Forest",
      "tagline": "If the animals disappear one by one, when will none be left?",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Math Concepts",
      "curriculum_tag": "Numbers — Counting and subtraction intro",
      "env_angle": "Extinction is what happens when animals are counted down to zero",
      "character_type": "A ranger counting elephants who notices the number gets smaller each year",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-math-002",
      "name": "Shapes in Nature",
      "tagline": "Hexagons, spirals and circles — nature loves maths",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Math Concepts",
      "curriculum_tag": "Geometry — 2D shapes",
      "env_angle": "Honeycombs, snowflakes, and shells show that nature is a perfect mathematician",
      "character_type": "A bee explaining why she builds hexagons",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-math-003",
      "name": "More or Less Water",
      "tagline": "Some places have too much rain, some have too little — why?",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Math Concepts",
      "curriculum_tag": "Measurement — Comparing quantities",
      "env_angle": "Climate change causes floods in some places and droughts in others — balance is being lost",
      "character_type": "Two villages — one flooded, one dry — that find a way to share",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-ss-001",
      "name": "My Neighbourhood and Nature",
      "tagline": "The park, the tree, the river — they are your neighbours too",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Social Studies",
      "curriculum_tag": "Community — Local environment",
      "env_angle": "Our neighbourhood's green spaces are lungs for the community",
      "character_type": "A child who maps all the trees on their street",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "kinder-ss-002",
      "name": "Where Does Our Food Come From?",
      "tagline": "Before the supermarket — there was a farm, a rain, and a seed",
      "age_min": 4,
      "age_max": 6,
      "grade": "Kindergarten",
      "subject": "Social Studies",
      "curriculum_tag": "Community — Food and farming",
      "env_angle": "Food travels long distances burning fuel — local food is better for the planet",
      "character_type": "A carrot who tells the story of its life from seed to plate",
      "difficulty": 2,
      "is_active": True
    },
    {
      "id": "p1-sci-001",
      "name": "Plants Need Sunlight, Water and Soil",
      "tagline": "Three ingredients for life — what if one runs out?",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Plant needs",
      "env_angle": "Deforestation removes shade and causes soil to dry out — plants die in a chain reaction",
      "character_type": "A plant scientist child who runs an experiment with three plants",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-sci-002",
      "name": "Parts of a Plant",
      "tagline": "Roots, stem, leaves, flower — each part has one critical job",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Plant structure",
      "env_angle": "When soil erodes, roots have nothing to hold — the whole plant falls",
      "character_type": "Each part of a plant as a team member in a relay race",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-sci-003",
      "name": "Human Body — Senses and the Environment",
      "tagline": "Your five senses help you experience — and protect — the planet",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Human senses",
      "env_angle": "When air is polluted, we can smell and taste it — our senses warn us when nature is in trouble",
      "character_type": "A child who detects pollution in the park using all five senses",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-sci-004",
      "name": "Animals — Characteristics and Movement",
      "tagline": "Every animal moves in a special way — why?",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Animal characteristics",
      "env_angle": "When habitats shrink, animals cannot move freely — they become trapped and endangered",
      "character_type": "A cheetah who can no longer run because the savannah has become a car park",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-sci-005",
      "name": "Materials Around Us",
      "tagline": "Wood, metal, plastic, glass — where do they come from and where do they go?",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Science & Nature",
      "curriculum_tag": "Physical Science — Materials and properties",
      "env_angle": "Plastic lasts 500 years — choosing materials wisely protects the planet",
      "character_type": "A plastic bottle and a glass bottle debating their futures",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-sci-006",
      "name": "Light and Darkness",
      "tagline": "Light travels in straight lines — and brings life with it",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Science & Nature",
      "curriculum_tag": "Physical Science — Light basics",
      "env_angle": "Solar panels capture light energy — understanding light helps us use it better",
      "character_type": "A ray of light on a world tour showing what it powers",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-sci-007",
      "name": "Water — States and Changes",
      "tagline": "The same water can be liquid, solid ice, or invisible steam",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Science & Nature",
      "curriculum_tag": "Physical Science — States of matter intro",
      "env_angle": "Glaciers are melting from solid to liquid — rising sea levels follow",
      "character_type": "A glacier who tells the story of shrinking every year",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-sci-008",
      "name": "Sound and Noise Pollution",
      "tagline": "Not all sounds are music — some are pollution",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Science & Nature",
      "curriculum_tag": "Physical Science — Sound basics",
      "env_angle": "Noise pollution from cities and ships disturbs whale communication and bird songs",
      "character_type": "A whale who can no longer hear her baby calling because of ship engines",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-sci-009",
      "name": "Food Chains — Who Eats Who?",
      "tagline": "Remove one link and the whole chain breaks",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Food chains",
      "env_angle": "Removing any species — even insects — collapses the food chain above it",
      "character_type": "A bee, a flower, a rabbit, and a fox whose chain is broken when bees disappear",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-sci-010",
      "name": "Weather Patterns",
      "tagline": "Weather is nature's mood — and it's changing",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Weather",
      "env_angle": "Extreme weather — floods, droughts, storms — is increasing due to climate change",
      "character_type": "A weather scientist child who notices the same month is hotter every year",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-math-001",
      "name": "Measuring Rainfall",
      "tagline": "Numbers tell us if there is enough water for everyone",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Math Concepts",
      "curriculum_tag": "Measurement — Length and volume",
      "env_angle": "Scientists measure rainfall to predict droughts and floods — maths saves lives",
      "character_type": "A child building a rain gauge and recording data for a week",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-math-002",
      "name": "Addition with Trees",
      "tagline": "If we plant 3 trees today and 4 tomorrow — how many did we give the Earth?",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Math Concepts",
      "curriculum_tag": "Numbers — Addition within 20",
      "env_angle": "Every tree planted adds to the planet's oxygen supply — adding up matters",
      "character_type": "A child tracking a tree-planting mission with a maths notebook",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-math-003",
      "name": "Recycling by the Numbers",
      "tagline": "How much rubbish does one family make in a week?",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Math Concepts",
      "curriculum_tag": "Numbers — Counting and data",
      "env_angle": "Tracking waste with numbers helps families reduce how much they throw away",
      "character_type": "A child who counts the family's plastic bottles for a week and is shocked",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-val-001",
      "name": "Standing Up for Nature",
      "tagline": "What do you do when you see someone hurting the environment?",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Courage and advocacy",
      "env_angle": "Speaking up when someone litters or harms nature is courage, not trouble-making",
      "character_type": "A shy child who finally speaks up when a classmate picks all the flowers",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-val-002",
      "name": "Gratitude for Nature",
      "tagline": "Thank you, sun. Thank you, rain. Thank you, tree.",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Gratitude",
      "env_angle": "Being grateful for nature makes us less likely to destroy it carelessly",
      "character_type": "A child who writes thank-you notes to parts of nature",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-ss-001",
      "name": "Communities Around the World",
      "tagline": "Children everywhere share the same planet — but face different problems",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Social Studies",
      "curriculum_tag": "Geography — World communities",
      "env_angle": "Children in different countries face different environmental challenges — drought, floods, deforestation",
      "character_type": "Two children — one in a rainforest, one in a desert — who write letters to each other",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p1-ss-002",
      "name": "Jobs That Protect the Planet",
      "tagline": "Rangers, scientists, farmers, cleaners — planet heroes come in every uniform",
      "age_min": 6,
      "age_max": 7,
      "grade": "Primary 1",
      "subject": "Social Studies",
      "curriculum_tag": "Community — Roles and jobs",
      "env_angle": "Environmental scientists, rangers, and green engineers are among the most important jobs on Earth",
      "character_type": "A child who tries on different planet-protecting jobs for a day",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p2-sci-001",
      "name": "Life Cycle of a Frog",
      "tagline": "Egg, tadpole, froglet, frog — the most dramatic transformation in nature",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Animal life cycles",
      "env_angle": "Frogs are indicator species — when frogs disappear from a pond, the water is polluted",
      "character_type": "A tadpole discovering legs for the first time",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p2-sci-002",
      "name": "Life Cycle of a Plant — Pollination",
      "tagline": "Bees carry the secret that makes fruit possible",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Plant life cycle and pollination",
      "env_angle": "One third of the world's food depends on bee pollination — pesticides are killing bees",
      "character_type": "A bee narrating its role as the planet's most important delivery worker",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p2-sci-003",
      "name": "States of Matter",
      "tagline": "Ice, water, steam — it is all the same thing wearing different clothes",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Science & Nature",
      "curriculum_tag": "Physical Science — Solids, liquids, gases",
      "env_angle": "Melting polar ice caps are one of the most visible signs of climate change",
      "character_type": "An ice cube who is terrified of becoming steam but learns to accept change",
      "difficulty": 3,
      "is_active": True
    },
    {
      "id": "p2-sci-004",
      "name": "Electricity — Where It Comes From",
      "tagline": "Flicking a switch is easy — but what happens behind the wall?",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Science & Nature",
      "curriculum_tag": "Physical Science — Electricity basics",
      "env_angle": "Most electricity still comes from burning coal — switching to solar and wind protects the planet",
      "character_type": "An electron racing through wires explaining its long journey from a coal mine or a solar panel",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "p2-sci-005",
      "name": "Magnets and Forces",
      "tagline": "An invisible force that pulls without touching",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Science & Nature",
      "curriculum_tag": "Physical Science — Magnetism",
      "env_angle": "Maglev trains use magnetic force — no fuel, no pollution, silent travel",
      "character_type": "A toy train that discovers it can float and travel without burning any fuel",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "p2-sci-006",
      "name": "Biodiversity — Why Different Species Matter",
      "tagline": "The planet needs every species like a body needs every organ",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Biodiversity",
      "env_angle": "One species going extinct triggers consequences across the entire ecosystem",
      "character_type": "A forest that gradually loses animals one by one until it collapses",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "p2-sci-007",
      "name": "Soil Types and Farming",
      "tagline": "Not all soil is equal — healthy soil is the basis of all food",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Soil and agriculture",
      "env_angle": "Overusing chemical fertilisers destroys soil health — organic farming heals it",
      "character_type": "A farmer's child who discovers that grandpa's old organic methods grow better crops",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "p2-sci-008",
      "name": "The Carbon Cycle",
      "tagline": "Carbon is in every living thing — so where does extra carbon go?",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Carbon cycle basics",
      "env_angle": "Burning fossil fuels releases stored carbon into the atmosphere, heating the Earth",
      "character_type": "A carbon atom narrating its journey from coal underground to the atmosphere",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "p2-math-001",
      "name": "Graphs of Temperature Over Time",
      "tagline": "Draw a line — is the Earth getting warmer?",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Math Concepts",
      "curriculum_tag": "Data — Simple graphs and charts",
      "env_angle": "Climate scientists use graphs to prove global warming — data is evidence",
      "character_type": "A child climate scientist presenting temperature data to her class",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "p2-math-002",
      "name": "Multiplication Through Nature",
      "tagline": "If one tree makes 100 seeds and each seed grows — how many trees in 10 years?",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Math Concepts",
      "curriculum_tag": "Numbers — Multiplication basics",
      "env_angle": "Nature multiplies — planting one tree today creates a forest over time",
      "character_type": "A child who plants one tree and calculates how many trees her grandchildren will inherit",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "p2-ss-001",
      "name": "Indigenous People and Nature Wisdom",
      "tagline": "Some communities have protected nature for thousands of years — what do they know?",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Social Studies",
      "curriculum_tag": "History & Culture — Indigenous knowledge",
      "env_angle": "Traditional ecological knowledge from indigenous communities is now being used by modern scientists",
      "character_type": "A child who visits a tribal elder and learns ancient forest protection techniques",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "p2-ss-002",
      "name": "Trade and Environmental Cost",
      "tagline": "The toy in your hands — how far did it travel to reach you?",
      "age_min": 7,
      "age_max": 8,
      "grade": "Primary 2",
      "subject": "Social Studies",
      "curriculum_tag": "Economics — Trade and global supply chains",
      "env_angle": "Shipping goods across the world burns enormous amounts of fuel — buying local helps",
      "character_type": "A toy that narrates its journey across three continents and two oceans",
      "difficulty": 4,
      "is_active": True
    },
    {
      "id": "p3-sci-001",
      "name": "The Atmosphere and Greenhouse Effect",
      "tagline": "Earth's blanket of air — what happens when it gets too thick?",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Atmosphere and climate",
      "env_angle": "Greenhouse gases trap heat — the more we burn, the thicker the blanket, the hotter the Earth",
      "character_type": "The atmosphere as a guardian who is being overwhelmed by too many gases",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-sci-002",
      "name": "Ecosystems — Everything is Connected",
      "tagline": "Pull one thread and the whole web shakes",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Ecosystems and interdependence",
      "env_angle": "Human interference in any part of an ecosystem — soil, water, air, species — affects the whole",
      "character_type": "A spider spinning a web that represents an ecosystem — and what happens when threads are cut",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-sci-003",
      "name": "Renewable vs Non-Renewable Energy",
      "tagline": "Some energy runs out — some lasts forever",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Science & Nature",
      "curriculum_tag": "Physical Science — Energy sources",
      "env_angle": "Switching from oil and coal to solar, wind and water power is the most urgent challenge of our time",
      "character_type": "Two rival energy companies — Coal Corp vs Sun Power — competing to power a city",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-sci-004",
      "name": "Ocean Ecosystems and Coral Reefs",
      "tagline": "The rainforest of the sea is bleaching white",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Marine ecosystems",
      "env_angle": "Ocean warming and acidification from CO2 is bleaching and killing coral reefs worldwide",
      "character_type": "A coral reef that slowly loses its colour and its residents as the sea warms",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-sci-005",
      "name": "Rock Cycle and Earth's History",
      "tagline": "Rocks tell a 4-billion-year story — if you know how to read them",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Rock cycle",
      "env_angle": "Rocks and fossils hold evidence of past climate changes — Earth has been through this before and life survived by adapting",
      "character_type": "A young geologist who discovers a fossil that tells a climate change story from 65 million years ago",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-sci-006",
      "name": "Human Impact on Land",
      "tagline": "In 200 years humans changed the land more than in the previous million",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Human impact",
      "env_angle": "Urbanisation, deforestation and mining are the three biggest land-destroyers — all driven by choices",
      "character_type": "A time-lapse story of a forest that becomes a city over 200 years — told by the oldest tree who survived",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-sci-007",
      "name": "Water Scarcity and Conservation",
      "tagline": "Only 3% of Earth's water is drinkable — and we are wasting it",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Science & Nature",
      "curriculum_tag": "Earth Science — Water conservation",
      "env_angle": "Over-extraction, pollution and climate change are reducing the world's fresh water supply",
      "character_type": "A village child who walks 5 km daily for water — and the connection to choices made in wealthy cities",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-sci-008",
      "name": "Adaptation and Survival",
      "tagline": "Animals have evolved over millions of years to survive — but can they evolve fast enough now?",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Science & Nature",
      "curriculum_tag": "Life Science — Adaptation",
      "env_angle": "Human-caused climate change is happening 10,000 times faster than natural change — animals cannot adapt fast enough",
      "character_type": "A polar bear whose ice is melting too fast to swim to the next floe",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-math-001",
      "name": "Fractions of the Earth",
      "tagline": "What fraction of Earth is ocean? Forest? Desert? And how is it changing?",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Math Concepts",
      "curriculum_tag": "Numbers — Fractions",
      "env_angle": "Forests once covered half the Earth — now less than one third remains",
      "character_type": "A cartographer child drawing pie charts of Earth's land use across centuries",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-math-002",
      "name": "Scale and Distance — The Solar System",
      "tagline": "Earth is tiny — and it is the only home we have",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Math Concepts",
      "curriculum_tag": "Measurement — Scale and large numbers",
      "env_angle": "There is no planet B — when you understand Earth's scale in the universe, protecting it becomes urgent",
      "character_type": "An astronaut looking back at Earth from space and understanding what is at stake",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-ss-001",
      "name": "Climate Justice",
      "tagline": "The people who pollute the least suffer the most — is that fair?",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Social Studies",
      "curriculum_tag": "Civics — Justice and fairness",
      "env_angle": "Low-income countries emit least CO2 but face worst climate impacts — island nations, drought regions",
      "character_type": "Two children — one in a wealthy polluting city, one on a flooding Pacific island — whose lives are connected",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-ss-002",
      "name": "Environmental Laws and Children's Rights",
      "tagline": "Children have the right to a clean planet — written in international law",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Social Studies",
      "curriculum_tag": "Civics — Rights and laws",
      "env_angle": "The UN Convention on the Rights of the Child includes the right to a clean environment",
      "character_type": "A child who discovers she has legal rights to a clean planet and writes a letter to her government",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-ss-003",
      "name": "How Countries Work Together on Climate",
      "tagline": "The Paris Agreement — when almost every country in the world made a promise",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Social Studies",
      "curriculum_tag": "Civics — International cooperation",
      "env_angle": "Climate change is the first problem in history that requires every country to cooperate simultaneously",
      "character_type": "A child delegate at a junior version of COP who must get all classmates to agree on one plan",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-val-001",
      "name": "Eco-Anxiety — Feeling Scared About the Planet",
      "tagline": "It's okay to feel worried — now let's turn it into power",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Managing fear and anxiety",
      "env_angle": "Many children feel overwhelmed by climate news — channelling that fear into action is healthy",
      "character_type": "A child who cries watching a documentary about dying forests and then starts a school garden",
      "difficulty": 5,
      "is_active": True
    },
    {
      "id": "p3-val-002",
      "name": "Being a Role Model",
      "tagline": "When you change, the people around you start to change too",
      "age_min": 8,
      "age_max": 9,
      "grade": "Primary 3",
      "subject": "Values & Emotions",
      "curriculum_tag": "Social Emotional — Leadership and influence",
      "env_angle": "One child's sustainable habits can influence an entire family and classroom",
      "character_type": "A child whose zero-waste lunch box starts a trend in her whole school",
      "difficulty": 5,
      "is_active": True
    }
  ]
}
